name: CI
on:
  - push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          # - '2.6'
          # - '2.7'
          # - '3.2'
          # - '3.3'
          # - '3.4'
          # - '3.5'
          # - '3.6'
          # - '3.7'
          # - '3.8'
          # - '3.9'
          # - '3.10'
          - '3.11'
          # - '3.12'
          # - '3.13'
    steps:
      - uses: actions/checkout@v4
      - run: pip install numpy pytest
      - run: pytest
  docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vondrak/docs
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r requirements.txt
      - run: jupyter nbconvert examples.ipynb --to rst
      - run: make html
