name: CI
on:
  - push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
    steps:
      - uses: actions/checkout@v4
      - run: pip install numpy pytest
      - run: pytest
  docs:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r requirements.txt
      - run: sudo apt install pandoc
      - run: jupyter nbconvert examples.ipynb --to rst
        working-directory: ./vondrak/docs
      - run: make html
        working-directory: ./vondrak/docs
